configfile: "config.yaml"


rule all:
    input:
        expand("raw_stat/{sample}.stat.txt", sample=config["samples"]),
        expand("clean_stat/{sample}.stat.txt", sample=config["samples"]),
        "result_vcfs/combined.vcf.gz",
        "result_vcfs/combined.indel.filtered.vcf.gz",
        "result_vcfs/combined.snp.filtered.vcf.gz"

include: "rules/bam_rmdup.rules"
include: "rules/bwa_index.rules"
include: "rules/bwa_mem.rules"
include: "rules/index_rmdup.rules"
include: "rules/clean_reads.rules"
include: "rules/combine_gvcf.rules"
include: "rules/faidx_index.rules"
include: "rules/haplo.rules"
include: "rules/indel_filter.rules"
include: "rules/indel_select.rules"
include: "rules/joint_calling.rules"
include: "rules/picard_index.rules"
include: "rules/samtools_index.rules"
include: "rules/samtools_sort.rules"
include: "rules/snp_filter.rules"
include: "rules/snp_select.rules"
include: "rules/stat_clean.rules"
include: "rules/stat_fastq.rules"